### PR TITLE
Update trigger key to work with mouse button

### PR DESCRIPTION
**Pull request by lekiet1214**

### CODE REVIEW

**Comment by dsdggdfgdrgdrgdrgdrg** [comment]
hi, why it says unable to get offsets?

**Comment by lekiet1214** [comment]
> hi, why it says unable to get offsets?

Can you elaborate with more details? I'm using this with no problem.

**Comment by dsdggdfgdrgdrgdrgdrg** [comment]
I dont know how to explain,  but in the moment i open and execute Main.,
the console says unable to get offsets

**Comment by lekiet1214** [comment]
@dsdggdfgdrgdrgdrgdrg 
You may be using the old version of this repo, not my committed version. Also, please check if your PC can access this [github link](https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/offsets.json)

`Unable to get offsets.` means the script cannot get data from GitHub.
<details><summary>Details</summary>
<p>

```python
try:
            self.offsets = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/offsets.json').json()
            self.clientdll = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/client.dll.json').json()
        except:
            print('Unable to get offsets.')
            exit()
``` 

</p>
</details>

**Comment by dsdggdfgdrgdrgdrgdrg** [comment]
didnt work and yes, i have permission

**Comment by GabrielDourado37** [comment]
@lekiet1214 I made a script following a similar logic, did you get a vac ban? Did you test if it works on Faceit?

**Comment by lekiet1214** [comment]
> @lekiet1214 I made a script following a similar logic, did you get a vac ban? Did you test if it works on Faceit?

You can't get detected by just reading memory. Didn't test with Faceit.

**Comment by GabrielDourado37** [comment]
@lekiet1214 My script that I had created stopped working after today's update, do you know what's happening?

**Pull request closed without merging**
